import Head from 'next/head'
import React, { useEffect, useState } from 'react';

//Swiper
import { Swiper, SwiperSlide } from 'swiper/react';
import { Autoplay, Pagination, Navigation } from 'swiper/modules';

//API
import { getHome } from '../pages/api/home';

//Componets
import Loading from '../components/loading';

const Home = () => {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const headerData = await getHome();
        if (headerData) {
          setData(headerData);
        }
      } catch (error) {
        console.error("API verileri alınırken hata oluştu:", error);
      }
    };

    fetchData();
  }, [data]);

  useEffect(() => {
    if (!data) {
      setLoading(true);
    } else {
      setLoading(false);
    }
  }, [data]);

  if (loading) {
    return <Loading />;
  }

  return (
    <div>
      <Head>
        <title>LCW WEBSİTE CLONE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data && (
        <>
          <div className="row">
            <Swiper
              centeredSlides={true}
              autoplay={{
                delay: 2500,
                disableOnInteraction: false,
              }}
              pagination={{
                clickable: true,
              }}
              navigation={true}
              modules={[Autoplay, Pagination, Navigation]}
              className="mySwiper"
            >
              {data.marketplace1.map((item, index) => (
                <SwiperSlide key={index} className="col-md-6 col-sm-12 mb-3">
                  <a href={item.url}>
                    <img
                      src={item.img.data.attributes.url}
                      alt={item.altText}
                    />
                  </a>
                </SwiperSlide>
              ))}
            </Swiper>
          </div>
          <div className="row mt-1">
            <Swiper
              centeredSlides={true}
              autoplay={{
                delay: 5000,
                disableOnInteraction: false,
              }}
              pagination={{
                clickable: true,
              }}
              navigation={false}
              modules={[Autoplay, Pagination, Navigation]}
              className="mySwiper"
            >
              {data.marketplace2.map((item, index) => (
                <SwiperSlide key={index} className="col-md-6 col-sm-12 mb-3">
                  <a href={item.url}>
                    <img
                      src={item.img.data.attributes.url}
                      alt={item.altText}
                    />
                  </a>
                </SwiperSlide>
              ))}
            </Swiper>
          </div>
          <div className="container">
            <div className="row mt-5">
              {data.banner.map((item, index) => (
                <div key={index} className="col-md-6 col-sm-12 mb-3">
                  <a href={item.url}>
                    <img
                      src={item.img.data.attributes.url}
                      alt={item.altText}
                    />
                  </a>
                </div>
              ))}
            </div>
          </div>
        </>
      )}
    </div>
  );
}

export default Home;

