import Head from 'next/head'
import Image from 'next/image'

import SwiperComponent from '../components/swiper'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        test
        <SwiperComponent />
      </main>

    </div>
  )
}
